<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Hardware;
use Carbon\Carbon;

class HardwareSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $hardwareData = [
            [
                'kode_hardware' => 'HW001',
                'nama_hardware' => 'Dell Inspiron 15 3000',
                'merk' => 'Dell',
                'model' => 'Inspiron 15 3000',
                'serial_number' => 'DL001234567',
                'spesifikasi' => 'Intel Core i5-1135G7, 8GB RAM, 256GB SSD, 15.6" HD Display',
                'kategori' => 'Laptop',
                'status' => 'Aktif',
                'tanggal_pembelian' => '2024-01-15',
                'harga_pembelian' => 8500000,
                'lokasi' => 'IT Office - Room 101',
                'pic_pengguna' => 'John Doe',
                'divisi' => 'IT',
                'keterangan' => 'Laptop untuk staff IT',
                'tanggal_garansi_mulai' => '2024-01-15',
                'tanggal_garansi_selesai' => '2026-01-15',
                'vendor' => 'PT. Dell Indonesia',
                'no_invoice' => 'INV-DELL-2024-001',
                'created_by' => 'Admin',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_hardware' => 'HW002',
                'nama_hardware' => 'HP ProDesk 400 G7',
                'merk' => 'HP',
                'model' => 'ProDesk 400 G7',
                'serial_number' => 'HP002345678',
                'spesifikasi' => 'Intel Core i7-10700, 16GB RAM, 512GB SSD, Windows 11 Pro',
                'kategori' => 'Komputer',
                'status' => 'Aktif',
                'tanggal_pembelian' => '2024-02-20',
                'harga_pembelian' => 12500000,
                'lokasi' => 'Accounting - Room 203',
                'pic_pengguna' => 'Jane Smith',
                'divisi' => 'Accounting',
                'keterangan' => 'Desktop untuk bagian accounting',
                'tanggal_garansi_mulai' => '2024-02-20',
                'tanggal_garansi_selesai' => '2026-02-20',
                'vendor' => 'PT. HP Indonesia',
                'no_invoice' => 'INV-HP-2024-002',
                'created_by' => 'Admin',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_hardware' => 'HW003',
                'nama_hardware' => 'Canon imageCLASS LBP6030',
                'merk' => 'Canon',
                'model' => 'imageCLASS LBP6030',
                'serial_number' => 'CN003456789',
                'spesifikasi' => 'Laser Printer, Monochrome, USB Connection, A4 Size',
                'kategori' => 'Printer',
                'status' => 'Maintenance',
                'tanggal_pembelian' => '2023-11-10',
                'harga_pembelian' => 1200000,
                'lokasi' => 'Admin Office - Room 105',
                'pic_pengguna' => 'Michael Brown',
                'divisi' => 'Admin',
                'keterangan' => 'Printer untuk keperluan administrasi umum',
                'tanggal_garansi_mulai' => '2023-11-10',
                'tanggal_garansi_selesai' => '2024-11-10',
                'vendor' => 'PT. Canon Indonesia',
                'no_invoice' => 'INV-CANON-2023-003',
                'created_by' => 'Admin',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_hardware' => 'HW004',
                'nama_hardware' => 'Cisco Catalyst 2960-X',
                'merk' => 'Cisco',
                'model' => 'Catalyst 2960-X-24TS-L',
                'serial_number' => 'CS004567890',
                'spesifikasi' => '24-Port Gigabit Switch, Layer 2, Managed Switch',
                'kategori' => 'Network',
                'status' => 'Aktif',
                'tanggal_pembelian' => '2024-03-05',
                'harga_pembelian' => 15000000,
                'lokasi' => 'Server Room - Rack A1',
                'pic_pengguna' => 'Network Admin',
                'divisi' => 'IT',
                'keterangan' => 'Switch utama untuk jaringan kantor',
                'tanggal_garansi_mulai' => '2024-03-05',
                'tanggal_garansi_selesai' => '2027-03-05',
                'vendor' => 'PT. Cisco Indonesia',
                'no_invoice' => 'INV-CISCO-2024-004',
                'created_by' => 'Admin',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_hardware' => 'HW005',
                'nama_hardware' => 'Epson EH-TW5700',
                'merk' => 'Epson',
                'model' => 'EH-TW5700',
                'serial_number' => 'EP005678901',
                'spesifikasi' => 'Full HD 1080p, 2700 Lumens, 3LCD Technology, HDMI/VGA',
                'kategori' => 'Proyektor',
                'status' => 'Aktif',
                'tanggal_pembelian' => '2024-04-12',
                'harga_pembelian' => 8000000,
                'lokasi' => 'Meeting Room A',
                'pic_pengguna' => 'Admin Meeting',
                'divisi' => 'General',
                'keterangan' => 'Proyektor untuk ruang meeting utama',
                'tanggal_garansi_mulai' => '2024-04-12',
                'tanggal_garansi_selesai' => '2026-04-12',
                'vendor' => 'PT. Epson Indonesia',
                'no_invoice' => 'INV-EPSON-2024-005',
                'created_by' => 'Admin',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_hardware' => 'HW006',
                'nama_hardware' => 'Samsung 24" Monitor',
                'merk' => 'Samsung',
                'model' => 'LF24T450FQE',
                'serial_number' => 'SM006789012',
                'spesifikasi' => '24" Full HD IPS, 75Hz, AMD FreeSync, Flicker Free',
                'kategori' => 'Monitor',
                'status' => 'Aktif',
                'tanggal_pembelian' => '2024-05-18',
                'harga_pembelian' => 2500000,
                'lokasi' => 'Marketing - Desk 5',
                'pic_pengguna' => 'Sarah Wilson',
                'divisi' => 'Marketing',
                'keterangan' => 'Monitor tambahan untuk workstation marketing',
                'tanggal_garansi_mulai' => '2024-05-18',
                'tanggal_garansi_selesai' => '2026-05-18',
                'vendor' => 'PT. Samsung Indonesia',
                'no_invoice' => 'INV-SAMSUNG-2024-006',
                'created_by' => 'Admin',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_hardware' => 'HW007',
                'nama_hardware' => 'Synology DS220+',
                'merk' => 'Synology',
                'model' => 'DiskStation DS220+',
                'serial_number' => 'SY007890123',
                'spesifikasi' => '2-Bay NAS, Intel Celeron J4025, 2GB RAM, RAID Support',
                'kategori' => 'Storage',
                'status' => 'Aktif',
                'tanggal_pembelian' => '2024-06-25',
                'harga_pembelian' => 4500000,
                'lokasi' => 'Server Room - Rack B2',
                'pic_pengguna' => 'IT Admin',
                'divisi' => 'IT',
                'keterangan' => 'Network Attached Storage untuk backup data',
                'tanggal_garansi_mulai' => '2024-06-25',
                'tanggal_garansi_selesai' => '2026-06-25',
                'vendor' => 'PT. Synology Indonesia',
                'no_invoice' => 'INV-SYNOLOGY-2024-007',
                'created_by' => 'Admin',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_hardware' => 'HW008',
                'nama_hardware' => 'Brother MFC-L2710DW',
                'merk' => 'Brother',
                'model' => 'MFC-L2710DW',
                'serial_number' => 'BR008901234',
                'spesifikasi' => 'All-in-One Laser Printer, WiFi, Auto Duplex, Scanner',
                'kategori' => 'Scanner',
                'status' => 'Rusak',
                'tanggal_pembelian' => '2023-08-15',
                'harga_pembelian' => 3200000,
                'lokasi' => 'HR Office - Room 301',
                'pic_pengguna' => 'HR Staff',
                'divisi' => 'HR',
                'keterangan' => 'Printer scanner untuk keperluan HR',
                'tanggal_garansi_mulai' => '2023-08-15',
                'tanggal_garansi_selesai' => '2024-08-15',
                'vendor' => 'PT. Brother Indonesia',
                'no_invoice' => 'INV-BROTHER-2023-008',
                'created_by' => 'Admin',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_hardware' => 'HW009',
                'nama_hardware' => 'Lenovo ThinkPad E14',
                'merk' => 'Lenovo',
                'model' => 'ThinkPad E14 Gen 3',
                'serial_number' => 'LN009012345',
                'spesifikasi' => 'AMD Ryzen 5 5500U, 8GB RAM, 512GB SSD, 14" FHD',
                'kategori' => 'Laptop',
                'status' => 'Retired',
                'tanggal_pembelian' => '2022-12-01',
                'harga_pembelian' => 9500000,
                'lokasi' => 'Storage Room',
                'pic_pengguna' => '-',
                'divisi' => 'Finance',
                'keterangan' => 'Laptop lama, sudah diganti dengan yang baru',
                'tanggal_garansi_mulai' => '2022-12-01',
                'tanggal_garansi_selesai' => '2023-12-01',
                'vendor' => 'PT. Lenovo Indonesia',
                'no_invoice' => 'INV-LENOVO-2022-009',
                'created_by' => 'Admin',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'kode_hardware' => 'HW010',
                'nama_hardware' => 'ASUS RT-AX6000',
                'merk' => 'ASUS',
                'model' => 'RT-AX6000',
                'serial_number' => 'AS010123456',
                'spesifikasi' => 'WiFi 6 Router, Dual Band, 6000 Mbps, 8 Gigabit Ports',
                'kategori' => 'Network',
                'status' => 'Aktif',
                'tanggal_pembelian' => '2024-07-30',
                'harga_pembelian' => 5500000,
                'lokasi' => 'Main Office - Network Cabinet',
                'pic_pengguna' => 'Network Admin',
                'divisi' => 'IT',
                'keterangan' => 'Router utama untuk akses internet kantor',
                'tanggal_garansi_mulai' => '2024-07-30',
                'tanggal_garansi_selesai' => '2027-07-30',
                'vendor' => 'PT. ASUS Indonesia',
                'no_invoice' => 'INV-ASUS-2024-010',
                'created_by' => 'Admin',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($hardwareData as $data) {
            Hardware::create($data);
        }
    }
}
