<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SaldoAwalFix extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // jenis_gram
        DB::table('jenis_gram')->insert(['kode'=>'BK110','namaLog'=>'BK110','namaMc'=>'BK110','jenisKertasLog'=>'BK','jenisKertasMc'=>'BK','gramKertas'=>'110','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'BK125','namaLog'=>'BK125','namaMc'=>'BK125','jenisKertasLog'=>'BK','jenisKertasMc'=>'BK','gramKertas'=>'125','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'BK135','namaLog'=>'BK135','namaMc'=>'BK135','jenisKertasLog'=>'BK','jenisKertasMc'=>'BK','gramKertas'=>'135','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'BK150','namaLog'=>'BK150','namaMc'=>'BK150','jenisKertasLog'=>'BK','jenisKertasMc'=>'BK','gramKertas'=>'150','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'BK200','namaLog'=>'BK200','namaMc'=>'BK200','jenisKertasLog'=>'BK','jenisKertasMc'=>'BK','gramKertas'=>'200','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'BK275','namaLog'=>'BK275','namaMc'=>'BK275','jenisKertasLog'=>'BK','jenisKertasMc'=>'BK','gramKertas'=>'275','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF100','namaLog'=>'MF100','namaMc'=>'MF100','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'100','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF105','namaLog'=>'MF105','namaMc'=>'MF105','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'105','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF110','namaLog'=>'MF110','namaMc'=>'MF110','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'110','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF112','namaLog'=>'MF112','namaMc'=>'MF112','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'112','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF115','namaLog'=>'MF115','namaMc'=>'MF115','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'115','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF120','namaLog'=>'MF120','namaMc'=>'MF120','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'120','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF122','namaLog'=>'MF122','namaMc'=>'MF122','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'122','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF125','namaLog'=>'MF125','namaMc'=>'MF125','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'125','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF130','namaLog'=>'MF130','namaMc'=>'MF130','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'130','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF135','namaLog'=>'MF135','namaMc'=>'MF135','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'135','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF140','namaLog'=>'MF140','namaMc'=>'MF140','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'140','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF145','namaLog'=>'MF145','namaMc'=>'MF145','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'145','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF150','namaLog'=>'MF150','namaMc'=>'MF150','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'150','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF152','namaLog'=>'MF152','namaMc'=>'MF152','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'152','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF160','namaLog'=>'MF160','namaMc'=>'MF160','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'160','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF180','namaLog'=>'MF180','namaMc'=>'MF180','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'180','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF190','namaLog'=>'MF190','namaMc'=>'MF190','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'190','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF200','namaLog'=>'MF200','namaMc'=>'MF200','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'200','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'MF90','namaLog'=>'MF90','namaMc'=>'MF90','jenisKertasLog'=>'MF','jenisKertasMc'=>'MF','gramKertas'=>'90','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML100','namaLog'=>'ML100','namaMc'=>'ML100','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'100','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML110','namaLog'=>'ML110','namaMc'=>'ML110','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'110','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML112','namaLog'=>'ML112','namaMc'=>'ML112','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'112','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML115','namaLog'=>'ML115','namaMc'=>'ML115','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'115','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML120','namaLog'=>'ML120','namaMc'=>'ML120','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'120','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML125','namaLog'=>'ML125','namaMc'=>'ML125','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'125','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML127','namaLog'=>'ML127','namaMc'=>'ML127','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'127','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML130','namaLog'=>'ML130','namaMc'=>'ML130','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'130','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML140','namaLog'=>'ML140','namaMc'=>'ML140','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'140','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML145','namaLog'=>'ML145','namaMc'=>'ML145','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'145','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML150','namaLog'=>'ML150','namaMc'=>'ML150','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'150','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML160','namaLog'=>'ML160','namaMc'=>'ML160','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'160','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'ML90','namaLog'=>'ML90','namaMc'=>'ML90','jenisKertasLog'=>'ML','jenisKertasMc'=>'ML','gramKertas'=>'90','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL100','namaLog'=>'TL100','namaMc'=>'BK100','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'100','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL110','namaLog'=>'TL110','namaMc'=>'BK110','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'110','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL115','namaLog'=>'TL115','namaMc'=>'BK115','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'115','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL120','namaLog'=>'TL120','namaMc'=>'BK120','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'120','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL125','namaLog'=>'TL125','namaMc'=>'BK125','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'125','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL135','namaLog'=>'TL135','namaMc'=>'BK135','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'135','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL140','namaLog'=>'TL140','namaMc'=>'BK140','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'140','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL145','namaLog'=>'TL145','namaMc'=>'BK145','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'145','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL150','namaLog'=>'TL150','namaMc'=>'TL150','jenisKertasLog'=>'TLA','jenisKertasMc'=>'TLA','gramKertas'=>'150','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL160','namaLog'=>'TL160','namaMc'=>'BK160','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'160','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL170','namaLog'=>'TL170','namaMc'=>'BK170','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'170','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL175','namaLog'=>'TL175','namaMc'=>'BK175','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'175','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL190','namaLog'=>'TL190','namaMc'=>'BK190','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'190','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL200','namaLog'=>'TL200','namaMc'=>'BK200','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'200','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL230','namaLog'=>'TL230','namaMc'=>'BK230','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'230','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TL275','namaLog'=>'TL275','namaMc'=>'BK275','jenisKertasLog'=>'TL','jenisKertasMc'=>'BK','gramKertas'=>'275','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'TLA150','namaLog'=>'TLA150','namaMc'=>'TLA150','jenisKertasLog'=>'TLA','jenisKertasMc'=>'TLA','gramKertas'=>'150','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'WK140','namaLog'=>'WK140','namaMc'=>'WK140','jenisKertasLog'=>'WK','jenisKertasMc'=>'WK','gramKertas'=>'140','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'WK150','namaLog'=>'WK150','namaMc'=>'WK150','jenisKertasLog'=>'WK','jenisKertasMc'=>'WK','gramKertas'=>'150','createdBy'=>'SEEDER']);
        DB::table('jenis_gram')->insert(['kode'=>'WK200','namaLog'=>'WK200','namaMc'=>'WK200','jenisKertasLog'=>'WK','jenisKertasMc'=>'WK','gramKertas'=>'200','createdBy'=>'SEEDER']);

        //
        DB::table('joint')->insert(['id'=>'1','kode'=>'DOUBLE STITCH 05','nama'=>'DOUBLE STITCH 05','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'2','kode'=>'DOUBLE STITCH 06','nama'=>'DOUBLE STITCH 06','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'3','kode'=>'DOUBLE STITCH 07','nama'=>'DOUBLE STITCH 07','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'4','kode'=>'DOUBLE STITCH 08','nama'=>'DOUBLE STITCH 08','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'5','kode'=>'DOUBLE STITCH 09','nama'=>'DOUBLE STITCH 09','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'6','kode'=>'DOUBLE STITCH 10','nama'=>'DOUBLE STITCH 10','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'7','kode'=>'DOUBLE STITCH 11','nama'=>'DOUBLE STITCH 11','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'8','kode'=>'DOUBLE STITCH 12','nama'=>'DOUBLE STITCH 12','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'9','kode'=>'DOUBLE STITCH 13','nama'=>'DOUBLE STITCH 13','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'10','kode'=>'DOUBLE STITCH 14','nama'=>'DOUBLE STITCH 14','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'11','kode'=>'DOUBLE STITCH 15','nama'=>'DOUBLE STITCH 15','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'12','kode'=>'DOUBLE STITCH 16','nama'=>'DOUBLE STITCH 16','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'13','kode'=>'DOUBLE STITCH 17','nama'=>'DOUBLE STITCH 17','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'14','kode'=>'DOUBLE STITCH ATAS BAWAH 10','nama'=>'DOUBLE STITCH ATAS BAWAH 10','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'15','kode'=>'DOUBLE STITCH ATAS BAWAH 11','nama'=>'DOUBLE STITCH ATAS BAWAH 11','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'16','kode'=>'DOUBLE STITCH ATAS BAWAH 12','nama'=>'DOUBLE STITCH ATAS BAWAH 12','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'17','kode'=>'DOUBLE STITCH ATAS BAWAH 13','nama'=>'DOUBLE STITCH ATAS BAWAH 13','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'18','kode'=>'DOUBLE STITCH ATAS BAWAH 14','nama'=>'DOUBLE STITCH ATAS BAWAH 14','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'19','kode'=>'DOUBLE STITCH ATAS BAWAH 15','nama'=>'DOUBLE STITCH ATAS BAWAH 15','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'20','kode'=>'DOUBLE STITCH ATAS BAWAH 17','nama'=>'DOUBLE STITCH ATAS BAWAH 17','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'21','kode'=>'DOUBLE STITCH ATAS BAWAH 6','nama'=>'DOUBLE STITCH ATAS BAWAH 6','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'22','kode'=>'DOUBLE STITCH ATAS BAWAH 7','nama'=>'DOUBLE STITCH ATAS BAWAH 7','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'23','kode'=>'DOUBLE STITCH ATAS BAWAH 9','nama'=>'DOUBLE STITCH ATAS BAWAH 9','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'24','kode'=>'DOUBLE STITCH ATAS BAWAH7','nama'=>'DOUBLE STITCH ATAS BAWAH7','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'25','kode'=>'GLUE','nama'=>'GLUE','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'26','kode'=>'GLUE-STITCH','nama'=>'GLUE-STITCH','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'27','kode'=>'GLUE-STITCH 03','nama'=>'GLUE-STITCH 03','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'28','kode'=>'GLUE-STITCH 04','nama'=>'GLUE-STITCH 04','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'29','kode'=>'GLUE-STITCH 06','nama'=>'GLUE-STITCH 06','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'30','kode'=>'GLUE-STITCH 10','nama'=>'GLUE-STITCH 10','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'31','kode'=>'No Joint','nama'=>'No Joint','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'32','kode'=>'STITCH 03','nama'=>'STITCH 03','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'33','kode'=>'STITCH 04','nama'=>'STITCH 04','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'34','kode'=>'STITCH 05','nama'=>'STITCH 05','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'35','kode'=>'STITCH 06','nama'=>'STITCH 06','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'36','kode'=>'STITCH 07','nama'=>'STITCH 07','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'37','kode'=>'STITCH 08','nama'=>'STITCH 08','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'38','kode'=>'STITCH 09','nama'=>'STITCH 09','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'39','kode'=>'STITCH 10','nama'=>'STITCH 10','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'40','kode'=>'STITCH 11','nama'=>'STITCH 11','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'41','kode'=>'STITCH 12','nama'=>'STITCH 12','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'42','kode'=>'STITCH 13','nama'=>'STITCH 13','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'43','kode'=>'STITCH 14','nama'=>'STITCH 14','createdBy'=>'SEEDER']);
        DB::table('joint')->insert(['id'=>'44','kode'=>'STITCHING','nama'=>'STITCHING','createdBy'=>'SEEDER']);

        // COLOR
        DB::table('color')->insert(['kode'=>'ABU02','nama'=>'ABU02','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ABU03','nama'=>'ABU03','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ABU04','nama'=>'ABU04','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ABU05','nama'=>'ABU05','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ABU06','nama'=>'ABU06','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ABU07','nama'=>'ABU07','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ABU08','nama'=>'ABU08','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ABU09','nama'=>'ABU09','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ABU10','nama'=>'ABU10','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU01','nama'=>'BRU01','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU02','nama'=>'BRU02','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU03','nama'=>'BRU03','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU04','nama'=>'BRU04','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU05','nama'=>'BRU05','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU06','nama'=>'BRU06','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU07','nama'=>'BRU07','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU10','nama'=>'BRU10','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU100','nama'=>'BRU100','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU102','nama'=>'BRU102','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU105','nama'=>'BRU105','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU107','nama'=>'BRU107','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU108','nama'=>'BRU108','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU109','nama'=>'BRU109','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU11','nama'=>'BRU11','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU110','nama'=>'BRU110','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU111','nama'=>'BRU111','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU112','nama'=>'BRU112','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU113','nama'=>'BRU113','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU114','nama'=>'BRU114','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU115','nama'=>'BRU115','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU116','nama'=>'BRU116','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU119','nama'=>'BRU119','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU12','nama'=>'BRU12','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU120','nama'=>'BRU120','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU121','nama'=>'BRU121','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU122','nama'=>'BRU122','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU123','nama'=>'BRU123','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU124','nama'=>'BRU124','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU125','nama'=>'BRU125','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU126','nama'=>'BRU126','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU127','nama'=>'BRU127','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU128','nama'=>'BRU128','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU129','nama'=>'BRU129','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU130','nama'=>'BRU130','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU132','nama'=>'BRU132','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU133','nama'=>'BRU133','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU134','nama'=>'BRU134','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU135','nama'=>'BRU135','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU136','nama'=>'BRU136','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU137','nama'=>'BRU137','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU138','nama'=>'BRU138','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU139','nama'=>'BRU139','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU14','nama'=>'BRU14','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU140','nama'=>'BRU140','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU141','nama'=>'BRU141','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU142','nama'=>'BRU142','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU143','nama'=>'BRU143','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU144','nama'=>'BRU144','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU145','nama'=>'BRU145','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU146','nama'=>'BRU146','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU147','nama'=>'BRU147','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU148','nama'=>'BRU148','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU149','nama'=>'BRU149','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU15','nama'=>'BRU15','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU150','nama'=>'BRU150','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU151','nama'=>'BRU151','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU17','nama'=>'BRU17','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU18','nama'=>'BRU18','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU20','nama'=>'BRU20','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU21','nama'=>'BRU21','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU22','nama'=>'BRU22','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU23','nama'=>'BRU23','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU24','nama'=>'BRU24','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU25','nama'=>'BRU25','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU26','nama'=>'BRU26','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU27','nama'=>'BRU27','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU28','nama'=>'BRU28','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU31','nama'=>'BRU31','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU32','nama'=>'BRU32','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU33','nama'=>'BRU33','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU34','nama'=>'BRU34','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU35','nama'=>'BRU35','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU36','nama'=>'BRU36','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU37','nama'=>'BRU37','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU38','nama'=>'BRU38','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU39','nama'=>'BRU39','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU41','nama'=>'BRU41','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU42','nama'=>'BRU42','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU43','nama'=>'BRU43','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU44','nama'=>'BRU44','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU45','nama'=>'BRU45','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU46','nama'=>'BRU46','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU47','nama'=>'BRU47','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU48','nama'=>'BRU48','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU49','nama'=>'BRU49','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU50','nama'=>'BRU50','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU51','nama'=>'BRU51','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU52','nama'=>'BRU52','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU53','nama'=>'BRU53','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU54','nama'=>'BRU54','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU55','nama'=>'BRU55','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU58','nama'=>'BRU58','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU59','nama'=>'BRU59','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU61','nama'=>'BRU61','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU62','nama'=>'BRU62','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU63','nama'=>'BRU63','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU64','nama'=>'BRU64','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU65','nama'=>'BRU65','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU66','nama'=>'BRU66','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU67','nama'=>'BRU67','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU68','nama'=>'BRU68','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU69','nama'=>'BRU69','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU70','nama'=>'BRU70','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU71','nama'=>'BRU71','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU72','nama'=>'BRU72','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU73','nama'=>'BRU73','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU74','nama'=>'BRU74','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU76','nama'=>'BRU76','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU77','nama'=>'BRU77','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU78','nama'=>'BRU78','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU80','nama'=>'BRU80','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU81','nama'=>'BRU81','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU82','nama'=>'BRU82','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU83','nama'=>'BRU83','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU86','nama'=>'BRU86','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU87','nama'=>'BRU87','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU88','nama'=>'BRU88','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU89','nama'=>'BRU89','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU90','nama'=>'BRU90','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU91','nama'=>'BRU91','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU92','nama'=>'BRU92','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU93','nama'=>'BRU93','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU94','nama'=>'BRU94','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU95','nama'=>'BRU95','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU96','nama'=>'BRU96','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU97','nama'=>'BRU97','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU99','nama'=>'BRU99','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT02','nama'=>'CKT02','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT04','nama'=>'CKT04','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT05','nama'=>'CKT05','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT07','nama'=>'CKT07','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT09','nama'=>'CKT09','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT10','nama'=>'CKT10','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT11','nama'=>'CKT11','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT12','nama'=>'CKT12','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT15','nama'=>'CKT15','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT17','nama'=>'CKT17','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT18','nama'=>'CKT18','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT19','nama'=>'CKT19','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT20','nama'=>'CKT20','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT21','nama'=>'CKT21','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT22','nama'=>'CKT22','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT23','nama'=>'CKT23','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT24','nama'=>'CKT24','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT25','nama'=>'CKT25','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT26','nama'=>'CKT26','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT28','nama'=>'CKT28','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT29','nama'=>'CKT29','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT30','nama'=>'CKT30','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT31','nama'=>'CKT31','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT32','nama'=>'CKT32','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT33','nama'=>'CKT33','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'CKT34','nama'=>'CKT34','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'GLD02','nama'=>'GLD02','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'GLD03','nama'=>'GLD03','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'GLD04','nama'=>'GLD04','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU01','nama'=>'HJU01','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU03','nama'=>'HJU03','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU06','nama'=>'HJU06','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU07','nama'=>'HJU07','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU08','nama'=>'HJU08','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU09','nama'=>'HJU09','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU11','nama'=>'HJU11','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU12','nama'=>'HJU12','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU13','nama'=>'HJU13','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU14','nama'=>'HJU14','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU15','nama'=>'HJU15','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU16','nama'=>'HJU16','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU17','nama'=>'HJU17','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU18','nama'=>'HJU18','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU19','nama'=>'HJU19','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU20','nama'=>'HJU20','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU21','nama'=>'HJU21','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU22','nama'=>'HJU22','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU23','nama'=>'HJU23','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU24','nama'=>'HJU24','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU25','nama'=>'HJU25','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU26','nama'=>'HJU26','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU27','nama'=>'HJU27','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU28','nama'=>'HJU28','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU29','nama'=>'HJU29','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU30','nama'=>'HJU30','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU31','nama'=>'HJU31','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU32','nama'=>'HJU32','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU33','nama'=>'HJU33','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU34','nama'=>'HJU34','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU36','nama'=>'HJU36','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU38','nama'=>'HJU38','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU39','nama'=>'HJU39','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU41','nama'=>'HJU41','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU42','nama'=>'HJU42','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU43','nama'=>'HJU43','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU44','nama'=>'HJU44','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU45','nama'=>'HJU45','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU46','nama'=>'HJU46','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU47','nama'=>'HJU47','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU48','nama'=>'HJU48','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU49','nama'=>'HJU49','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU51','nama'=>'HJU51','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU52','nama'=>'HJU52','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU53','nama'=>'HJU53','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU54','nama'=>'HJU54','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU55','nama'=>'HJU55','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU56','nama'=>'HJU56','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU57','nama'=>'HJU57','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU59','nama'=>'HJU59','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU60','nama'=>'HJU60','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU61','nama'=>'HJU61','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU62','nama'=>'HJU62','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU63','nama'=>'HJU63','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU64','nama'=>'HJU64','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU65','nama'=>'HJU65','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU67','nama'=>'HJU67','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU68','nama'=>'HJU68','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU69','nama'=>'HJU69','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU70','nama'=>'HJU70','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU71','nama'=>'HJU71','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU72','nama'=>'HJU72','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU73','nama'=>'HJU73','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU74','nama'=>'HJU74','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HTM01','nama'=>'HTM01','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HTM03','nama'=>'HTM03','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG01','nama'=>'KNG01','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG02','nama'=>'KNG02','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG03','nama'=>'KNG03','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG04','nama'=>'KNG04','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG05','nama'=>'KNG05','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG06','nama'=>'KNG06','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG07','nama'=>'KNG07','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG08','nama'=>'KNG08','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG09','nama'=>'KNG09','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG10','nama'=>'KNG10','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG11','nama'=>'KNG11','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG12','nama'=>'KNG12','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG14','nama'=>'KNG14','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG15','nama'=>'KNG15','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG17','nama'=>'KNG17','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG18','nama'=>'KNG18','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG19','nama'=>'KNG19','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG20','nama'=>'KNG20','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG21','nama'=>'KNG21','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG22','nama'=>'KNG22','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG23','nama'=>'KNG23','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG24','nama'=>'KNG24','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG25','nama'=>'KNG25','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG26','nama'=>'KNG26','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG28','nama'=>'KNG28','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG29','nama'=>'KNG29','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG30','nama'=>'KNG30','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG31','nama'=>'KNG31','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG32','nama'=>'KNG32','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG33','nama'=>'KNG33','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG35','nama'=>'KNG35','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG36','nama'=>'KNG36','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG37','nama'=>'KNG37','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'KNG38','nama'=>'KNG38','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH01','nama'=>'MRH01','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH02','nama'=>'MRH02','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH03','nama'=>'MRH03','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH04','nama'=>'MRH04','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH06','nama'=>'MRH06','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH07','nama'=>'MRH07','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH08','nama'=>'MRH08','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH09','nama'=>'MRH09','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH10','nama'=>'MRH10','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH12','nama'=>'MRH12','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH13','nama'=>'MRH13','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH14','nama'=>'MRH14','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH15','nama'=>'MRH15','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH16','nama'=>'MRH16','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH17','nama'=>'MRH17','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH18','nama'=>'MRH18','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH20','nama'=>'MRH20','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH21','nama'=>'MRH21','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH22','nama'=>'MRH22','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH23','nama'=>'MRH23','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH24','nama'=>'MRH24','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH25','nama'=>'MRH25','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH26','nama'=>'MRH26','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH27','nama'=>'MRH27','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH28','nama'=>'MRH28','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH29','nama'=>'MRH29','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH30','nama'=>'MRH30','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH34','nama'=>'MRH34','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH35','nama'=>'MRH35','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH38','nama'=>'MRH38','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH40','nama'=>'MRH40','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH41','nama'=>'MRH41','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH42','nama'=>'MRH42','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH46','nama'=>'MRH46','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH47','nama'=>'MRH47','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH48','nama'=>'MRH48','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH49','nama'=>'MRH49','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH50','nama'=>'MRH50','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH51','nama'=>'MRH51','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH52','nama'=>'MRH52','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH54','nama'=>'MRH54','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH55','nama'=>'MRH55','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH56','nama'=>'MRH56','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH57','nama'=>'MRH57','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH58','nama'=>'MRH58','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH59','nama'=>'MRH59','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH60','nama'=>'MRH60','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH61','nama'=>'MRH61','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH64','nama'=>'MRH64','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH65','nama'=>'MRH65','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH66','nama'=>'MRH66','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH67','nama'=>'MRH67','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH68','nama'=>'MRH68','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH69','nama'=>'MRH69','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH70','nama'=>'MRH70','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH71','nama'=>'MRH71','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH72','nama'=>'MRH72','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH73','nama'=>'MRH73','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH74','nama'=>'MRH74','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH77','nama'=>'MRH77','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH79','nama'=>'MRH79','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH81','nama'=>'MRH81','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH82','nama'=>'MRH82','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH83','nama'=>'MRH83','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH84','nama'=>'MRH84','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH85','nama'=>'MRH85','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH86','nama'=>'MRH86','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH87','nama'=>'MRH87','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH88','nama'=>'MRH88','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH90','nama'=>'MRH90','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH91','nama'=>'MRH91','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH92','nama'=>'MRH92','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH94','nama'=>'MRH94','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH95','nama'=>'MRH95','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH96','nama'=>'MRH96','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'MRH97','nama'=>'MRH97','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG01','nama'=>'ORG01','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG02','nama'=>'ORG02','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG03','nama'=>'ORG03','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG04','nama'=>'ORG04','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG05','nama'=>'ORG05','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG06','nama'=>'ORG06','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG07','nama'=>'ORG07','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG08','nama'=>'ORG08','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG09','nama'=>'ORG09','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG10','nama'=>'ORG10','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG11','nama'=>'ORG11','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG12','nama'=>'ORG12','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG13','nama'=>'ORG13','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG14','nama'=>'ORG14','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'ORG15','nama'=>'ORG15','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'PNK01','nama'=>'PNK01','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'PNK02','nama'=>'PNK02','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'PNK04','nama'=>'PNK04','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'PNK05','nama'=>'PNK05','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'PNK06','nama'=>'PNK06','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'PNK07','nama'=>'PNK07','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'PNK08','nama'=>'PNK08','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'PNK09','nama'=>'PNK09','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'POLOS','nama'=>'POLOS','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'PTH01','nama'=>'PTH01','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'UNG01','nama'=>'UNG01','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'UNG02','nama'=>'UNG02','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'UNG06','nama'=>'UNG06','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'UNG08','nama'=>'UNG08','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'UNG09','nama'=>'UNG09','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'UNG10','nama'=>'UNG10','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'UNG11','nama'=>'UNG11','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'UNG12','nama'=>'UNG12','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'UNG13','nama'=>'UNG13','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'UNG14','nama'=>'UNG14','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'UNG16','nama'=>'UNG16','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'VIO01','nama'=>'VIO01','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'VIO02','nama'=>'VIO02','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'VIO03','nama'=>'VIO03','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'VIO04','nama'=>'VIO04','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'VIO07','nama'=>'VIO07','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU75','nama'=>'HJU75','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'BRU152','nama'=>'BRU152','mudaTua'=>0,'createdBy'=>'SEEDER']);
        DB::table('color')->insert(['kode'=>'HJU76','nama'=>'HJU76','mudaTua'=>0,'createdBy'=>'SEEDER']);

        //TOP
        DB::table('top')->insert(['id'=>'1','nama'=>'10 Hari','hari'=>'10','createdBy'=>'SEEDER']);
        DB::table('top')->insert(['id'=>'2','nama'=>'14 Hari','hari'=>'14','createdBy'=>'SEEDER']);
        DB::table('top')->insert(['id'=>'3','nama'=>'30 Hari','hari'=>'30','createdBy'=>'SEEDER']);
        DB::table('top')->insert(['id'=>'4','nama'=>'45 Hari','hari'=>'45','createdBy'=>'SEEDER']);
        DB::table('top')->insert(['id'=>'5','nama'=>'60 Hari','hari'=>'60','createdBy'=>'SEEDER']);
        DB::table('top')->insert(['id'=>'6','nama'=>'75 Hari','hari'=>'75','createdBy'=>'SEEDER']);
        DB::table('top')->insert(['id'=>'7','nama'=>'90 Hari','hari'=>'90','createdBy'=>'SEEDER']);
        DB::table('top')->insert(['id'=>'8','nama'=>'0 Hari','hari'=>'0','createdBy'=>'SEEDER']);
        DB::table('top')->insert(['id'=>'9','nama'=>'5 Hari','hari'=>'5','createdBy'=>'SEEDER']);
        DB::table('top')->insert(['id'=>'10','nama'=>'7 Hari','hari'=>'7','createdBy'=>'SEEDER']);

    }
}
